### ISSUE TITLE
Iframe > bouton "Version détaillée" ne revoie pas vers monimpacttransport.fr

### ISSUE THREAD

**Issue by martinregner** [datagir/monimpacttransport#100]

**Comment by florianpanchout** [comment]
Corrigé juste après la mise en ligne normalement. Cache cache cache ?

**Comment by martinregner** [comment]
Toujours pas 🤔 
![image](https://user-images.githubusercontent.com/46482115/151405904-f9ecefe3-5bb0-4d0b-8e60-a0d3af6fe638.png)

**Comment by florianpanchout** [comment]
Oups, j'avais lu trop vite et je pensais que tu parlais du bouton. Déso déso déso :/ 

C'est corrigé 

(mais par contre pourquoi on a le bouton "En savoir plus sur ce simulateur" et le "Version détaillée" ? Est ce qu'on n'enlèverais pas le bouton ?)

**Comment by martinregner** [comment]
> (mais par contre pourquoi on a le bouton "En savoir plus sur ce simulateur" et le "Version détaillée" ? Est ce qu'on n'enlèverais pas le bouton ?)

C'est dommage que tu aies corrigé, car c'est sans doute la meilleure version en effet :) (sauf si on veut 2 CTA visuellement différents pour être sûr d'être vu...)

**Comment by florianpanchout** [comment]
C'est déjà modifié pour ne plus avoir le bouton :)
