### ISSUE TITLE
Plus possible de faire une saisie libre des km

### ISSUE THREAD

**Issue by laem** [datagir/monimpacttransport#105]
Retour utilisateur : 

> Et on ne peut plus entrer de distance manuellement 😱 je suis super triste

N'est-il pas possible de créer un hybride slider / input, au clic relaché par exemple ? 

C'est vrai que personnellement, je trouve le manque d'input direct dommage aussi.

**Comment by martinregner** [comment]
le retour m'a aussi été fait.
Si possible d'avoir les deux cela pourrait être intéressant en effet

**Comment by Clem-mrtn** [comment]
#107

**Comment by florianpanchout** [comment]
J'ai ajouté une option pour afficher un champs texte. (ça me paraissait hasardeux d'afficher le champs texte directement dans le slider)
