### ISSUE TITLE
Accessibilité : développements des quick-wins

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#109]
Suite au retour de l'audit optimiser le simulateur avec la mise à jour des différents critères 

=> dupliquer le modèle sur les autres simulateurs pour exporter les bonnes pratiques. 
**Estimation : 1 journée (environ)**
**Deadline** : début juin 2022 pendant/avant le transfert

**Comment by Clem-mrtn** [comment]
- Corriger les derniers critères du fichier excel  
- MAJ des fichiers excel avec les critères corrigés

**Comment by florianpanchout** [comment]
Les corrections du fichier xls sont moins exhaustives que celles du pdf. Si je dois moi même faire l'audit du site pour trouver les derniers éléments à corriger pour chaque critère (s'il y en a), je vais y passer beaucoup de temps. Je propose d'envoyer le site tel quel (avec la liste de critères corrigés ci-dessus)

**Comment by Clem-mrtn** [comment]
Oui oui pas de soucis on renvoie ce qui est à corriger sur les fichiers Excel  !

**Comment by florianpanchout** [comment]
xlsx mis à jour avec les critères corrigés (dans la colonne `suivi des correctifs`) 
[2022-03-08_mon-impact-transport_grille-RGAA4-1.xlsx](https://github.com/datagir/monimpacttransport/files/8730413/2022-03-08_mon-impact-transport_grille-RGAA4-1.xlsx)
