### ISSUE TITLE
Supprimer la fonctionnalité "Contact" sur l'iframe 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#112]
Idem que pour le site Datagir : on se retrouve avec quelques messages "parasites" 
Pour faire un premier filtre : est-ce qu'on pourrait supprimer la fonction contact sur les _iframe_ (ou alors renvoyer au clic sur le site MIT) ? 

Comme ça, pour nous contacter il faudrait passer déjà par le site MIT

**Comment by florianpanchout** [comment]
Done
