### ISSUE TITLE
Certificat d'accessibilité 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#113]
- [x] Afficher la mention "Partiellement Conforme" 
- [x] Créer la page d'accessibilité au format indiqué dans les instructions de publication 
- [ ] Les tenir informer quand la page d'accessibilité est en ligne

**Comment by Clem-mrtn** [comment]
[2022-05-30_Grille_recette_Monimpacttransport_RGAA4.1.xlsx](https://github.com/datagir/monimpacttransport/files/8799549/2022-05-30_Grille_recette_Monimpacttransport_RGAA4.1.xlsx)
[instructions-publication-declaration-mention.pdf](https://github.com/datagir/monimpacttransport/files/8799550/instructions-publication-declaration-mention.pdf)

**Comment by florianpanchout** [comment]
Done
