### ISSUE TITLE
Bug dans la personnalisation de l'intégration iframe 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#114]
Retour d'un de nos réutilisateurs : 
Volonté d'intégrer l'iframe sur la partie itinéraire et de cocher par défaut covoiturage. Ils ont tenté d'intégrer en remplacant **"ce simulateur"** par **"ce résultat"** 

MAIS : 

> •	En effet, après avoir suivi vos indications, l'iframe ne s'intègre toujours pas en affichant l'onglet itinéraire par défaut,
•	Après avoir cocher la case "covoiturage", ce filtre apparait bien, cependant lorsque l'on clique sur "+", ce dernier passe de "1 covoitureur" à "20 covoitureurs",
•	Enfin, cela fait apparaitre à l'écran tous les modes de transport bien que cela n'ait pas été coché.

**Comment by Clem-mrtn** [comment]
@florianpanchout est-ce que tu pourrais regarder ce qu'il en est quand tu as un moment ? 
Je me suis fait relancer par l'utilisateur

**Comment by florianpanchout** [comment]
Corrigé !
