### ISSUE TITLE
Affichage construction + utilisation sur la même barre

### ISSUE THREAD

**Issue by martinregner** [datagir/monimpacttransport#117]
Pour la comparaison entre les modes de transport (notamment VE et voiture thermique), je pense qu'il serait plus parlant d'avoir deux couleur dans la barre : le bleu actuel pour l'utilisation + une autre couleur (autre bleu ?) pour la fabrication.

**Comment by florianpanchout** [comment]
Done.

Par contre ça met en lumière le problème d'afficher la construction / km. On s'attend à ce que la composition des barres change lorsque l'on change le nombre de km.

**Comment by martinregner** [comment]
C'est vrai que c'est parlant... et un peu décevant en même temps vu que ça ne bouge pas.
On attend les données /véhicule...

**Comment by florianpanchout** [comment]
Suite à la remarque de @Clemog, j'ai ajouté la construction des autres véhicules. Ça ne change pas énormément de chose en dehors de l'avion qui devient d'un coup le choix écolo :) 

https://construction2--ecolab-transport.netlify.app/

Vous en pensez quoi ?

Ça remet une pièce dans le débat pour l'affichage ou non des trainés :)

**Comment by Clemog** [comment]
Yes ! Ça me parait plus pertinent lais effectivement, afficher l'impact des trainées me paraît indispensable :
- Pour les personnes qui sont sensibilisées et qui connaissent ce sujet, c'est important de leur donner facilement l'info (j'ai déjà une la remarque, 'c'est bien mais il manque les trainées' pour des personnes qui n'avaient pas vu la case à cocher)
- Pour les personnes qui découvrent, ça permet de mettre en lumière cette info (quoiqu'on dise de l'incertitude sur la valeur), ce qui je pense est important pour notre "raison d'être" : sensibiliser et faire connaître les données environnementales. La connaissance que l'impact des traînées existe est une information (d'autant que la doc de la base carbone sur la base carbone est complète et on peut facilement partager également  ce qui est dit dans la doc)

**Comment by Clemog** [comment]
Et pour reprendre la discussion sur la prise en compte par défaut de la construction, je pense que c'est important de l'afficher directement (peut-être encore plus dans MCCO2), les informations sont disponibles et la fabrication du véhicule fait partie de l'impact au km d'un déplacement, j'ai l'impression que le message est biaisé si on l'omet, notamment pour l'électrique

**Comment by florianpanchout** [comment]
Pour l'affichage par défaut des trainées, nous sommes contraints par la loi (relative aux affichages transport). Mais intégrer MIT à MCC permettrait de changer ça (il deviendrait un affichage généraliste) si je ne me trompe pas.
(je laisse @martinregner corriger si besoin)

**Comment by florianpanchout** [comment]
Issue traitée dans MCC
