### ISSUE TITLE
Ajouter la mobilité maritime (voilier, bateau de croisière, etc.)

### ISSUE THREAD

**Issue by fjg** [datagir/monimpacttransport#12]
2 points :
- Ajout de l'impact des bateaux (mettre quelques sortes de bateau : bateau de croisière, bateau cargo ou porte-conteneur, petit bateau à moteur, voilier)

Mes questions :
- D'ailleurs, pouvez-vous me dire où se situeraient à peu près les bateaux sur la visualisation "voyager dans le monde" de 10 000 km ?

**Comment by fjg** [comment]
Ferry : allant régulièrement en corse, je n'arrive pas à savoir s'il vaut mieux voyager en avion ou ferry. Pourriez-vous ajouter ce mode de trnasport à votre simulateur?

**Comment by fjg** [comment]
Serait-il possible d'avoir les données pour les flux maritimes ?

**Comment by fjg** [comment]
Bonjour, il manque pour moi le transport en bateau, bien que difficile à apprécier selon qu'il transporte des véhicules également (ferry) ou non et selon sa taille. Mais il est indispensable quand on veut comparer un trajet vers l'Irlande ou l'Islande par exemple. Beaucoup pense que le bateau est plus écologique mais je n'en suis pas si sûr. Par ailleurs, en attendant une mise à jour incorporant les liaisons maritimes, auriez vous des études sur le sujets qui me permettrons d'avancer sur mes projets de voyage. Merci par avance.

**Comment by fjg** [comment]
Ajouter comme mode de transport le ferry. Exemple, pour aller en corse est-ce mieux de prendre le ferry ou l’avion ?

**Comment by fjg** [comment]
la prise en compte des bateaux. Une façon de traiter le plurimodale notamment pour les voyage en Europe où on pourrait faire de la voitrure du train du bateau...

**Comment by florianpanchout** [comment]
Fait
