### ISSUE TITLE
Affichage du % d'iframe 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#125]
Vérifier le % d'affichage en iframe depuis matomo et sur le site https://datagir.ademe.fr/stats

**Comment by florianpanchout** [comment]
J'ai modifié la méthode de calcul. Elle est maintenant beaucoup plus proche de la réalité.

Elle n'est pas exacte mais ça demanderait plus de travail (quelques heures) pour modifier le code. Je ne pense pas que ça soit pertinent ici vu que le site est amené à changer prochainement
