### ISSUE TITLE
Echanges API Google Maps

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#126]
Message d'Antoine Augusti de la SE transport data.gouv 

> Hello,
J'ai vu sur votre GitHub que vous aviez des difficultés avec l'API Google Places en terme de quotas. https://github.com/datagir/monimpacttransport/issues/74
On a des bons contacts à Google, en particulier chez Maps. Je pense qu'on pourrait vous obtenir la gratuité, peut-être même sans contrepartie.
Vous souhaitez une mise en relation ? 

Ca me semble intéressant ! Qu'en pensez-vous ?
A quel point l'API Google Maps est bloquante @florianpanchout ?

**Comment by florianpanchout** [comment]
Mail répondu. Ce serait peut être plus pratique de garder l'ensemble du sujet sur #74 ?
