### ISSUE TITLE
Ajout construction fait disparaitre les transports en commun

### ISSUE THREAD

**Issue by Clemog** [datagir/monimpacttransport#129]
J'ai peut-être loupé l'info mais je ne comprends pas pourquoi l'ajout de la construction fait disparaitre les autres modes de transport en commun ?

Selon, le fait que les chiffres utilisés notamment [ici](https://www.francetvinfo.fr/monde/environnement/crise-climatique/infographies-bill-gates-kylie-jenner-taylor-swift-bernard-arnault-totalenergies-l-ete-ou-les-voyages-en-jet-prive-des-ultra-riches-sont-devenus-un-scandale-climatique_5324140.html) ne prennent pas en compte l'ACV totale (même avec une durée de vie moyenne) est un problème ..

**Comment by florianpanchout** [comment]
Tu as tellement loupé l'info que tu as participé à [la conversation sur le sujet](https://github.com/datagir/monimpacttransport/issues/117) :) 

[La nouvelle version sur MCC](https://nextjs-monconvertisseurco2.netlify.app/categories/transport) devrait corriger le problème

**Comment by Clemog** [comment]
yes j'ai relu cette issue mais je ne voyais pas l'info de cette disparition qui me perturbe
