### ISSUE TITLE
Emissions à pied/vélo nulle ?

### ISSUE THREAD

**Issue by fjg** [datagir/monimpacttransport#15]
Est on sur que l homme à pied ou à velo a un impact CO2 nul? Car si tous les jours on va a velo au taff, le soir/midi on aura plus faim, la nourriture est responsable pour 30% des emissions de CO2 globales (tout prit en compte) sans compter les courbatures qui necessiteront de manger des prots pour refaire les muscles (la viande a le pire impact CO2 de toute la nourriture)

**Comment by fjg** [comment]
cf. https://github.com/betagouv/ecolab-transport/issues/38

**Comment by florianpanchout** [comment]
"Sont inclus les émissions directes, et la production et distribution de carburant et d'électricité. La construction des véhicules (voiture, vélo, batterie, train, avion...) et des infrastructures (routes, rails, aéroports...) n'est pas incluse."

À voir si l'on considère la nourriture comme un carburant.

(À noter que l'on est peut être pas à ce niveau de détail ?)

**Comment by martinregner** [comment]
Difficile de savoir s'il y a des études sérieuses sur ce sujet ... Ne peut-on pas grignoter en voiture, train aussi ? et la pause salée ou sucrée de l'avion ?...

Le complément de périmètre incluant la fabrication des modes de transport permettra de répondre en partie à cela
