### ISSUE TITLE
Pouvoir indiquer autre chose que des kms (difficile pour le train)

### ISSUE THREAD

**Issue by fjg** [datagir/monimpacttransport#17]
Je souhaite réaliser une enquête interne et demander aux collègues de calculer l'équivalent CO2 de leur trajet grâce à votre site. Je m'interroge sur leur capacité à indiquer le nombre de km pour le TER. Il me semble que cela pourrait poser problème ou générer des réponses assez variables pour un même trajet selon la logique choisi par le répondant.
En tout cas bravo pour l'outil !

**Comment by martinregner** [comment]
Ce point est en bonne partie résolu par la possibilité de parcours "de... à"

Il resterait possible d'ajouter une fonction "je voyage ... h" et de voir tous les transports ; nécessite des hypothèses pour chaque mode qui peuvent peut-être préter à débat

**Comment by florianpanchout** [comment]
Ça me semble très compliqué à estimer non ? Et j'ai du mal à voir le cas d'usage ou l'on ne connais ni la distance, ni l'adresse de départ et d'arrivée.
