### ISSUE TITLE
Nombre moyen de passagers - taux de remplissage

### ISSUE THREAD

**Issue by fjg** [datagir/monimpacttransport#26]
Il manque le nombre moyen de personne par mode de transport.
Pour le bus thermique, quel est le nombre de personnes moyen retenu ?
Merci

**Comment by fjg** [comment]
Cela serait bien d'avoir le nombre de passagers pris en compte dans le calcul pour les modes de transport collectifs tels que l'avion, le train, l'autobus, etc. En effet, ce n'est pas la même quantité de CO2 si on considère 50 ou 150 passagers. Cela serait même bien si on pourrait les changer.

**Comment by fjg** [comment]
Pour les transports collectifs, quels sont les taux de remplissage pris en compte ?

**Comment by florianpanchout** [comment]
On a les données pour ça ? J'ai l'impression que ça n'est pas précisé dans la Base Carbone.

**Comment by martinregner** [comment]
je l'ai ajouté pour les autobus et autocar où c'est précisé dans les hypothèses de la Base Carbone, mais pas trouvé pour le reste. J'ai demandé...

**Comment by martinregner** [comment]
Retour du centre de ressources GES : pas de données suffisantes à ce jour

**Comment by florianpanchout** [comment]
Je suis le seul à trouver bizarre qu'ils arrivent à trouver un impact par passager sans connaitre le nombre de passager ?

**Comment by martinregner** [comment]
Voici la réponse complète du centre de ressource GES :

>**les données ne sont pas fournis avec un "taux de remplissage"... mais plutôt à partir d'une "fréquentation globale"** :

> - Pour le train, d'après la méthode utilisée (ci jointe), les facteurs d'émissions par personne sont générées à partir des données sur la "fréquentation annuelle réelle" sans que des chiffres de nombre de passager soient proposés. On retrouve en revanche dans cette note méthodologique, le nombre de personnes moyens par voiture (route) : 1,28 à 1,4 selon les cas en Ile de France . 

> - Pour l'avion, de la même façon, on va raisonner par fréquentation globale par type de transport (et non pas par avion pris indépendamment) : 179,6 millions de passagers en 2019 (https://eco-calculateur.dta.aviation-civile.gouv.fr/les-chiffres-cles )  répartis selon des pondérations

**Comment by florianpanchout** [comment]
> le nombre de personnes moyens par voiture (route) : 1,28 à 1,4 selon les cas en Ile de France .

C'est super problématique pour notre simulateur non ?

**Comment by florianpanchout** [comment]
Et même pour l'ensemble des données. Ça rends notre réutilisation plutôt mensongère...

**Comment by martinregner** [comment]
Euh... pourquoi ? 🤔 C'est quoi que tu trouves "mensonger" ?

Tous les facteurs d'émissions, quel que soit le secteur, sont réalisés comme cela, sur la base d'hypothèses et de données réelles.
Pour apporter des ordres de grandeur tel qu'on le fait, c'est particulièrement adapté.

**Comment by florianpanchout** [comment]
Effectivement, j'avais mal compris le principe de calcul pour l'avion. My bad

Mais la question de la voiture se pose quand même. On prends explicitement en compte le fait qu'il n'y a qu'un seul passager dans la voiture, alors que les chiffres sont pour "1.28 à 1.4"

**Comment by martinregner** [comment]
Ah OK. C'est que tu as pas coupé au bon endroit : 
> **dans cette note méthodologique**, le nombre de personnes moyens par voiture (route) : 1,28 à 1,4 selon les cas

...mais pas dans les facteurs qu'on a pris **dans la Base Carbone** directement. C'est bien pour une voiture directement :
![image](https://user-images.githubusercontent.com/46482115/124769224-9623f180-df39-11eb-9e58-4ea8362b86ca.png)

**Comment by florianpanchout** [comment]
Oui bah exprimez vous avec des phrases courtes et des mots simples les experts !

Ça marche. Du coup il faut mettre à jour les notes de MIT pour préciser qu'on se base sur la "fréquentation annuelle réelle" ?

**Comment by martinregner** [comment]
J'ai l'impression que c'est de la précision de précision, que 1% d'1% des visiteurs cherchent.
Les notes sont déjà peu regardées ; ce type de précision me semble enfoncer une porte ouverte.

Mais volontiers à tester dans les ateliers utilisateurs pour voir ce qu'il manque / peut être mieux précisé !
