### ISSUE TITLE
Voiture et bus (Bio) GNV

### ISSUE THREAD

**Issue by fjg** [datagir/monimpacttransport#28]
Il serait vraiment très intéressant d'ajouter une catégorie supplémentaire comme les voitures au bio GNV qui sont alimentés localement par les méthanisations des paysans français.
Pourquoi ? Et bien parcequ' il y a un réel enjeux climatique et social.
80% de CO2 en moins / diesel euro6
95% de particules en moins / diesel euro6
50% de Nox en moins / diesel euro6
50% de bruit en moins / diesel

**Comment by fjg** [comment]
@martinregner : en lien avec #10 ou pas ?

**Comment by florianpanchout** [comment]
@martinregner J'ajoute une option avec "Pas de donnée disponible pour ce mode de transport" ?

**Comment by florianpanchout** [comment]
(On a la data pour le bus GNV visiblement : https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=gnv). Je l'ai ajouté.

J'en ai aussi profité pour ajouter le bus électrique qui est dispo dans la base

**Comment by martinregner** [comment]
Pour info @florianpanchout, tu as pris aussi la fabrication pour le bus élec ... que l'on a pas dans les autres modes de transport 😉 
(je vais corriger dans les FE)
