### ISSUE TITLE
Option Forçage radiatif : ?

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#3]
A mon sens c'est un langage assez technique et pas du tout à la portée de tout le monde
Ayant vocation à être intégré sur des sites plutôt grand public je trouve ça trop complexe de le proposer comme option (avec la case à cocher) 
=> soit on le met par défaut et on fait une petite note explicative dans la méthodo ? 
=>soit on ne le met pas et on fait une petite note explicative ? (j'avoue j'ai 0 idée de l'impact si c'est absent dans méthodo)

**Comment by fjg** [comment]
Pour 9721 km, un paris/tokyo, vous estimez à 1.9T de CO2.
Pour la même distance sur le site https://eco-calculateur.dta.aviation-civile.gouv.fr/
l'estimation est à 760kg !
La différence est conséquente. Qui faut il croire ?
Merci de me donner votre avis. Je suis contraint de faire des voyages entre Nouméa et la France et j'aimerai viser au plus juste mon bilan carbone.

**Comment by florianpanchout** [comment]
@martinregner un avis ?

Selon moi l'option doit être présente : 
1) Pour contenter les gens qui se plaindraient soit de sa présence, soit de son absence
2) Pour sensibiliser les gens qui ne connaissent pas ce truc (comme moi)

Et la question serait plutôt : Est ce qu'elle doit être active par défaut ou non ?

**Comment by martinregner** [comment]
On pourrait préférer le terme "avec trainée"... même si n'est guerre plus clair (sympa ta proposition d'explications 🤣 )

Dans la précédente version, elle était "active par défaut" mais en montrant les deux. C'est toujours un grand débat, qui amène confusion certes mais aussi beaucoup de critiques.

Le précédent consensus d'afficher les deux était plutôt bien, ce serait idéal de le reprendre (avec deux couleurs de barre), soit sur une même barre comme avant, soit sur deux barre différentes (mais moins compréhensible)

Il faudrait la garder par défaut, et peut-être plutôt mettre le choix au niveau de l'avion, en distinguant les deux cas en deux lignes ?
![image](https://user-images.githubusercontent.com/46482115/110609813-e195e100-818d-11eb-8fc7-61a81c8b0cf6.png)

**Comment by florianpanchout** [comment]
L'option est maintenant cochée par défaut avec possibilité de l'enlever directement sur la barre de l'avion

**Comment by martinregner** [comment]
L'option est plus facilement accessible comme ça 👍 

- Changer "Forçage radiatif" --> **Impact des traînées**
- Vu la spécificité du sujet, pourrait-on garder le fait d'avoir **deux couleurs de barre** ?

**Comment by florianpanchout** [comment]
J'ai séparé la barre en deux. Ça te va ?

**Comment by martinregner** [comment]
On verra les retours si besoin de distinguer davantage
