### ISSUE TITLE
Distance Paris New-York ou Sydney en avion

### ISSUE THREAD

**Issue by fjg** [datagir/monimpacttransport#35]
je m'interroge sur le calcul de distance de source-destination, pour l'avion Paris New-York affiche 8k km env. alors que l'aller-retour c'est 11700 km cf. https://fr.distance.to/Avion - https://fr.distance.to/Paris/New-York
idem sur https://fr.distance.to/Paris/Sydney

**Comment by florianpanchout** [comment]
La distance est calculée à vol d'oiseau (via https://github.com/Turfjs/turf/tree/master/packages/turf-distance)
