### ISSUE TITLE
Paramètres : usage des pictos

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#39]
Dans le menu paramètre je comprends pas trop l'usage du picto cadenas ?
Le picto "oeil" c'est pour décider de faire apparaître ou non le moyen de transport, ça je comprends bien.
Le picto cadenas quelle est son utilité ? 

=> et du coup, en terme d'UI est-ce que c'est assez clair ?

**Comment by florianpanchout** [comment]
Oui je galère à trouver une façon simple de faire comprendre ce picto. C'est pour que le moyen de transport s'affiche tout le temps, peu importe la distance entrée.

En gros c'est pour faire plaisir à tous les gens qui veulent voir le vélo passé 30km (peut être espèrent-ils qu'il dépasse un jour 0 gCO2e...)

J'ai rajouté un tooltip, faute de mieux

**Comment by martinregner** [comment]
La tooltip est bien je trouve 👍

**Comment by Clem-mrtn** [comment]
Yes très bien comme ça, c'est plus clair ! 
Par contre je pense qu'il faudrait **deux tooltip :** 

- Par défaut les cadenas sont "en transparence" parce qu'aucun des modes de transports ne sont bloqués au départ. 
Donc là je mettrais ta phrase : _"Afficher en permanence ce mode de transport blabla"_ 

- Une fois qu'on clique sur le picto le cadenas "se colore", le transport est donc bloqué. 
Je mettrais donc une nouvelle phrase de tooltip qui invite à l'action de débloquer le transport _"Débloquer l'affichage permanent blabla"_ ou un truc comme ça :)

**Comment by florianpanchout** [comment]
Fait mais je peine à trouver une phrase compréhensible. 

J'ai mis :

"N'afficher le mode de transport que s'il est pertinent par rapport à la distance"

Mais j'ai l'impression que c'était plus clair quand il n'y avait qu'un seul tooltip

**Comment by martinregner** [comment]
Je trouve ça assez clair 👍

**Comment by Clem-mrtn** [comment]
Moi aussi je trouve ça assez clair :+1: 
Je vais faire le test un peu autour de moi mais on peut laisser comme ça pour l'instant !
