### ISSUE TITLE
Option Covoitureur(euses) 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#4]
L'option est top et plus claire que sur le précédent avec les têtes flotantes 
Mais je trouverais ça encore mieux qu'on puisse le sélectionner directement sur les moyens de transports concernant plutôt que d'aller dans _**Personnaliser**_ et de sélectionner les "Covoitureur(euses)".

=> Pour rester aussi claire que dans le menu de personnalisation et éviter l'aspect tête flottante, p-e rajouter simplement 
un "+ Covoitureur(euses)" avec les têtes à sélectionner, en dessous des barres pour voir directement l'effet que ça a sur la diminution de l'émission ou alors à côté ?

**Comment by florianpanchout** [comment]
Done

**Comment by Clem-mrtn** [comment]
L'animation est top ! 
Et on voit bien la diminution de l'impact, quand on rajoute des "covoitureurs"
=> Par contre je trouve que c'est pas encore 100% intuitif de cliquer sur le véhicule / ou le paramètre pour avoir accès à l'option.

Pour plus d'immédiateté, on pourrait pas se rajouter un petit bouton "+" ou truc comme ça, qui ouvrirait sur l'animation ?

**Comment by florianpanchout** [comment]
Fait
