### ISSUE TITLE
Affichage de l'avion

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#41]
Je me faisais la réflexion que pour des distances comme pour Paris - Bordeaux (pareil Paris-Nice) par exemple c'est dommage que l'avion ne ressorte pas automatiquement 
=> c'est typiquement le genre de comportement qu'on voudrait changer pour que les gens basculent sur du train vs de l'avion par exemple 

C'est quoi 1000 Km min pour que l'avion apparaisse automatiquement ?

**Comment by florianpanchout** [comment]
Ça devait être à partir de 500, mais il y avait un problème effectivement. C'est corrigé

**Comment by laem** [comment]
Je me permets de rouvrir cette issue suite à un retour utilisateur :

**Comment by florianpanchout** [comment]
L'avion s'affiche maintenant à partir de 400km (ça répond aussi au message d'Ishan)
