### ISSUE TITLE
"Je veux intégrer ce simul à mon sit" : Rajouter contact datagir 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#42]
Du coup comme on s'est dit, peut-être rajouter en dessous des différentes thématiques proposées, un contact Datagir : 
"Une question ? Vous voulez en savoir plus ? Contactez nous : datagir@ademe.fr _(ou contact@datagir.ademe.fr)_ ?

**Comment by florianpanchout** [comment]
@martinregner @Clem-mrtn Pour cette part, je propose d’avoir un footer beaucoup plus détaillé commun aux 3 simulateurs (NGC étant à part côté design)

>###  D’ou viennent ces données ?
> 
> Ce simulateur réutilise les données de la base carbone (https://www.bilans-ges.ademe.fr/fr/accueil/contenu/index/page/presentation/siGras/0 ou https://datagir.ademe.fr/jeux-de-donnees/ ?). Il s’agit d’une base de données publique de facteurs d'émissions, nécessaires à la réalisation d’un bilan d’émissions de gaz à effet de serre (GES) et plus généralement tout exercice de comptabilité carbone.
> L’ADEME blablabla écologie et tout blablabla ils ont plein de jeux de données en accès libre sur data.ademe.fr. 
> 
> **Qui sommes nous ?**
> 
> Datagir est un service public gratuit, porté par l’ADEME et l’incubateur de la DINUM beta.gouv.fr.  Notre mission est de diffuser les informations et données environnementales en open-data de l’ADEME pour encourager l’amélioration continue et l’innovation. Pour cela, nous accompagnons toutes les applications & services dans leur démarche responsable par l'appropriation et l’intégration de ces données afin d’apporter l’information au plus près des citoyens.
> 
> En savoir plus => https://datagir.ademe.fr/qui-sommes-nous
> 
> **Nous contacter** 
> 
> Vous souhaitez nous contacter pour blablabla intégration données ? Écrivez nous à datagir@ademe.fr
> 
> 
> Bouton “J’ai un retour sur ce simulateur” (ou mieux niveau wording ?) => ouvre Popin avec formulaire de contact. Selon le sujet du message choisi dans un menu déroulant, on a un petit texte qui s’affiche (exemple : “Ce simulateur n’a pas pour but d’être exhaustif et ne recense pas l’intégralité des modes de transports existant”)

**Comment by martinregner** [comment]
Dans l'idée j'aime bien !
Il faudra p-e travailler des textes plus courts, et mettre en police plus petite. Sinon ça pourrait faire un gros bloc non ?
Ou ça pourrait se dérouler quand on clique dessus ?

**Comment by florianpanchout** [comment]
C'est en ligne !

Il me faudrait la liste des objets possibles (et le message "FAQ" correspondant si besoin).

Et est on sur du bien fondé de créer une issue github anonyme à chaque nouveau message ? Ce ne serait pas plus interessant de faire le tri parmi les messages avant de nous mêmes créer des issues si besoin ?

**Comment by Clem-mrtn** [comment]
Désolée je viens seulement de me pencher sur le sujet ! 
J'imaginais quelque chose de plus simple et peut-être plus light : 

=> Une fois qu'on clique sur le gros bouton INTEGRER CE SIMULATEUR A MON SITE, la slide s'ouvre avec les différents thèmes et juste en dessous, on ajoutait _" Vous souhaitez aller plus loin et échanger avec nous blabalab contactez nous à datagir@ademe.fr "_

=> Pas de bloc QUI SOMMES NOUS : je vois pas trop l'utilité de le rajouter sur la LP du simulateur, s'ils veulent savoir ils vont sur le site de Datagir. Je trouve que ça alourdi pas mal la page non ?

=> Nous contacter : Cette partie là c'est pour les retours de bugs ou alors les suggestions de la communauté **mais pas pour le biz dev**. A mon sens il ne faut donc pas faire figurer datagir@ademe.fr (on le met que pour les intégrations). Pour cette partie c'est soit relié au compte GIT soit contact@datagir  ?
Et du coup peut-être clarifier d'avantage que "Nous contacter" => mettre par exemple "Un retour?" et les gens remplissent le formulaire avec leur bug ou leur recco...

**Comment by Clem-mrtn** [comment]
Pour les issues, je crois qu'initialement ça pointait sur contact@ et ça rentrait automatiquement dans un tableau qui est consultable sur Airtable avant d'être intégré à la mano sur GIT sous forme d'issues ?

**Comment by florianpanchout** [comment]
> Une fois qu'on clique sur le gros bouton INTEGRER CE SIMULATEUR A MON SITE, la slide s'ouvre avec les différents thèmes et juste en dessous, on ajoutait " Vous souhaitez aller plus loin et échanger avec nous blabalab contactez nous à datagir@ademe.fr "

Pourquoi limiter la visibilité du contact si c’est au final l’action que l’on attend de l’utilisateur ?

> Pas de bloc QUI SOMMES NOUS : je vois pas trop l'utilité de le rajouter sur la LP du simulateur, s'ils veulent savoir ils vont sur le site de Datagir. Je trouve que ça alourdi pas mal la page non ?

Et quel est le pourcentage de personne qui vont cliquer sur le lien comparé au nombre de personne qui vont lire ce paragraphe ? C'est autant de prospects potentiels de perdus.

> Nous contacter : Cette partie là c'est pour les retours de bugs ou alors les suggestions de la communauté mais pas pour le biz dev. A mon sens il ne faut donc pas faire figurer datagir@ademe.fr (on le met que pour les intégrations). Pour cette partie c'est soit relié au compte GIT soit contact@datagir ? Et du coup peut-être clarifier d'avantage que "Nous contacter" => mettre par exemple "Un retour?" et les gens remplissent le formulaire avec leur bug ou leur recco...

Pareil, pourquoi ne pas regrouper les deux types de contact pour ensuite rediriger automatiquement vers 2 mails différents selon le type de contact ?

La longueur d’une page n’a aucune incidence sur son efficacité ; c’est la facilité à trouver l’information qui compte. En faisant figurer l’ensemble des informations à la suite dans des paragraphes court et balisés, je pense qu'on l'apporte de la façon la plus claire et directe possible.

**Comment by martinregner** [comment]
OK avec @Clem-mrtn, ça fait un gros bloc, les boutons ne se distinguent plus c'est dommage.

--

> => Une fois qu'on clique sur le gros bouton INTEGRER CE SIMULATEUR A MON SITE, la slide s'ouvre avec les différents thèmes et juste en dessous, on ajoutait " Vous souhaitez aller plus loin et échanger avec nous blabalab contactez nous à datagir@ademe.fr "

+1
Proposition de texte : Vous souhaitez aller plus loin dans l'intégration de ce calculateur ou des données ? [Contactez-nous](https://datagir.ademe.fr/#contact) en bouton (ou lien simple ?) vers https://datagir.ademe.fr/#contact

--
> => Pas de bloc QUI SOMMES NOUS : je vois pas trop l'utilité de le rajouter sur la LP du simulateur, s'ils veulent savoir ils vont sur le site de Datagir. Je trouve que ça alourdi pas mal la page non ?

Oui... ou ils cliquent sur le logo.

--

> => Nous contacter : Cette partie là c'est pour les retours de bugs ou alors les suggestions de la communauté mais pas pour le biz dev. A mon sens il ne faut donc pas faire figurer datagir@ademe.fr (on le met que pour les intégrations). Pour cette partie c'est soit relié au compte GIT soit contact@datagir ?
Et du coup peut-être clarifier d'avantage que "Nous contacter" => mettre par exemple "Un retour?" et les gens remplissent le formulaire avec leur bug ou leur recco...

Tel quel c'est en effet mélangé, cf. proposition du haut pour le bizdev.
Je propose pour ici : 
### Un bug ? une proposition d'évolution ?
Ce simulateur est développé de manière ouverte (open source). L’ensemble du code est [disponible librement](https://github.com/datagir/monimpacttransport).
Pour nous signaler un bug, nous faire une suggestion ou donner votre avis sur ce simulateur : 

Le titre bref de votre question, remarque, correction
`Bla bla`

La description complète de votre remarque
`Bla bla`
`Bla bla`

_Cette contribution sera publique : n'y mettez pas d'informations sensibles_


(je suis reparti de https://nosgestesclimat.fr/contribuer  ; pas besoin a priori d'avoir le mail pour un retour de bug ... et comme ça il est clair qu'ils ne peuvent pas attendre de retour)

Et tout ça va directement dans github, avec un label "Retour formulaire" par ex. Dans contact@, ça peut spammer tout le monde et on ne sera pas qui doit s'en saisir + il faudra en faire des issues...

Qu'en pensez-vous @florianpanchout @Clem-mrtn ?

**Comment by martinregner** [comment]
Pardon @florianpanchout , j'avais commencé mon commentaire avant et j'avais pas vu ton retour.
En complément : 

> Pourquoi limiter la visibilité du contact si c’est au final l’action que l’on attend de l’utilisateur ?

L'action attendue c'est l'intégration. Le contact, j'ai peur que l'on se retrouve avec tous les retours sur datagir@ et ça va complètement nous spammer pour le bizdev.
S'il est motivé pour intégrer, il voit le contact. Bingo :)

> C'est autant de prospects potentiels de perdus.

Je suis partagé, je vois ton point. Mais je pense qu'on perd davantage de prospects avec ces § un peu longs, et qui ne trouveront plus aussi facilement le "intégrer"

**Comment by florianpanchout** [comment]
J’ai mis en ligne une nouvelle version. 

- J’ai mis le bouton d’intégration tout en haut et le qui sommes nous tout en bas. Impossible de dire que le premier est moins visible ou que le deuxième prend trop de place :)
- J’ai ajouté le texte de contact de Martin dans le volet d’intégration.
- J’ai restructuré le texte de “Comment intégrer ces données”
- J’ai modifié le texte du bloc Contact pour enlever l’adresse mail. Comme ça impossible de spammer datagir@ademe.fr. Seul les messages avec certains objets choisis iront vers cette adresse. Pour les autres (retours, bugs, etc…), je pense honnêtement que le plus simple est soit de le connecter à mon mail, soit à un airtable/trello. Je ne vois toujours pas l’interêt de créer une issue git à chaque fois qu’un utilisateur ne trouve pas sa marque de vélo préférée.

**Comment by martinregner** [comment]
> J’ai modifié le texte du bloc Contact pour enlever l’adresse mail. Comme ça impossible de spammer datagir@ademe.fr

A refaire aussi ici non ? 🤔 
![image](https://user-images.githubusercontent.com/46482115/112492570-aa285680-8d81-11eb-81bf-9504a0c8ba8b.png)

Possible d'avoir le même "[contactez-nous](https://datagir.ademe.fr/#contact)" que dans le volet ?

--

> Pour les autres (retours, bugs, etc…), je pense honnêtement que le plus simple est soit de le connecter à mon mail, soit à un airtable/trello. Je ne vois toujours pas l’interêt de créer une issue git à chaque fois qu’un utilisateur ne trouve pas sa marque de vélo préférée.

Certes ;)
Le problème c'est qu'avec l'ancien Airtable, on ne regardait que très peu les retours... Ca fait un outil à part, en plus.
Dans une option Airtable, autant mettre un lien vers un questionnaire externe pour ne pas avoir le bloc contact et alléger la page

**Comment by florianpanchout** [comment]
C'est un frein très important de devoir changer de site pour accéder à un formulaire de contact. Même chose pour le "Qui somme nous" si on se contentait de renvoyer vers le site Datagir. Je pense que l'on améliore grandement l'accès à ces informations en les proposant directement sur la page.

Vu que ces blocs sont en bas de page, ils n'enlèvent rien aux bloc placés au dessus. L'utilisateur moyen qui n'est pas intéressé par ces sections ne scrollera même pas jusqu'à la.

Pour Airtable, je ne pense pas que le problème soit résolu en créant automatiquement des issues sur Github. Je les regarde encore moins la au final.

Avoir la possibilité de hiérarchiser l'information (airtable : retours non filtrés, github : retours approuvés et donc à faire) apporte de la clarté. Alors que si tout est sur Github, on mélange tout et on finit par ne rien traiter.

**Comment by Clem-mrtn** [comment]
Pour le bloc _"Qui Sommes Nous"_ tout en bas, c'est moins gênant comme ça
Effectivement si on perd la personne à ce niveau là c'est pas très grave et ça peut permettre de centraliser l'information

Par contre : 

- Je grossirai le bouton INTEGRER CE SIMULATEUR A MON SITE pour le mettre plus en avant (il y a 3 boutons qui s'enchaînent _En savoir plus_, _Je calcule mon empreinte Carbone_, _Intégrer_..) 

- Dans le volet "intégrer ce simulateur" : pour le coup j'aurais mis directement l'adresse mail datagir@ademe.fr pour que les prospects qualifiés nous envoie plus facilement un message. Si on le redirige sur la page Contact, on risque de perdre des gens, et en plus remplir des formulaires c'est super relou ! Quand je tente de contacter les gens et qu'il n'y a pas d'adresse mail défini et que je dois passer par un formulaire c'est ultra démotivant.

- Pour le bloc "Nous contacter", je comprends pas trop pourquoi on a les mêmes infos que pour celui intégrer dans le volet intégration ? Pour moi ce bloc c'était pour les bugs, retours & suggestions ? Et donc c'est pas censé taper sur Datagir@ademe.fr mais sur Airtable ou Git 
Je mettrais simplement (sans titre de section) : "Vous souhaitez nous contacter pour nous signaler un bug, nous faire une suggestion ou donner votre avis sur ce simulateur ? Utilisez le formulaire ci‑dessous (ou alors pointer directement sur un form airtbale ou git) :" 

=> @florianpanchout pour les retours de bug, si c'est galère à traiter peut-être établir un process de retours qui te facilite le job ?

**Comment by florianpanchout** [comment]
> Dans le volet "intégrer ce simulateur" : pour le coup j'aurais mis directement l'adresse mail datagir@ademe.fr pour que les prospects qualifiés nous envoie plus facilement un message. Si on le redirige sur la page Contact, on risque de perdre des gens, et en plus remplir des formulaires c'est super relou ! Quand je tente de contacter les gens et qu'il n'y a pas d'adresse mail défini et que je dois passer par un formulaire c'est ultra démotivant.

Pourquoi ne pas mettre les deux ? "Vous pouvez nous écrire à datagir@ademe.fr ou utiliser le formulaire en bas de page". Perso c'est le lien mailto qui me perd (je n'ai pas de client mail configuré). Pas beaucoup d'études sur le sujet mais les gens sont apparemment 50/50.

>Pour le bloc "Nous contacter", je comprends pas trop pourquoi on a les mêmes infos que pour celui intégrer dans le volet intégration ? Pour moi ce bloc c'était pour les bugs, retours & suggestions ? Et donc c'est pas censé taper sur Datagir@ademe.fr mais sur Airtable ou Git

Et pour les gens qui ne veulent pas intégrer le simulateur mais souhaitent quand même nous contacter ? Encore une fois, il est possible, selon le sujet choisi, de renvoyer vers datagir@ademe.fr ou vers airtable/github. Ça ne polluera pas votre boite mail. Je ne vois vraiment pas ce que ça enlève de laisser l'option de nous contacter ici.

>pour les retours de bug, si c'est galère à traiter peut-être établir un process de retours qui te facilite le job ?

Pour moi Airtable + Mail à mon adresse, ça fait le job. Je me charge après de créer des issues Github pour les issues qui méritent d'être traitées.

**Comment by florianpanchout** [comment]
Créer des issues automatiquement, ça amène à ce genre de chose : https://github.com/datagir/monimpacttransport/issues/16

La personne attend clairement un retour qu'on ne pourra pas lui apporter et à la place on a une issue dont on ne peut rien faire.

**Comment by Clem-mrtn** [comment]
_"Pourquoi ne pas mettre les deux ? "Vous pouvez nous écrire à datagir@ademe.fr ou utiliser le formulaire en bas de page". Perso c'est le lien mailto qui me perd (je n'ai pas de client mail configuré). Pas beaucoup d'études sur le sujet mais les gens sont apparemment 50/50._"
=> J'ai peur qu'à mettre trop d'options on le perde un peu, mais on peut lui mettre le mailto datagir@ademe.fr ou lui dire de nous contacter via le formulaire (redirection sur le formulaire de notre site Datagir) ? 
**"Vous souhaitez aller plus loin dans l'intégration de ce calculateur ou des données ? N'hésitez pas à nous contacter à @datagir ou à remplir notre formulaire"** 

=> **Pour le bouton "Je veux intégrer ce simulateur"** en fait je faisais faire le test un peu autour de moi et je me disais pour éviter qu'il soit noyé dans la masse d'information pourquoi ne pas l'intégrer sous le simulateur directement.
Juste au dessus des _"30%..."_ et en dessous du petit paragraphe _"...ne correspond pas à la réalité des transports disponibles..."_ (et en un peu plus gros)

=> Aussi pour uniformiser les sources d'informations, j'incorporerai le paragraphe **"Comment intégrer ces données à mon site ou application** " dans le slider, juste en dessous des thèmes et de _"Vous souhaitez aller plus loin dans l'intégration de ce calculateur ou des données ? N'hésitez pas à nous contacter à @datagir ou à remplir notre formulaire"_ Plus logique qu'il soit à la suite du script, et des thèmes

**Comment by florianpanchout** [comment]
Pour la visibilité du bouton intégration, j'ai fait un test sur http://mesfruitsetlegumesdesaison.fr/

Dites moi ce que vous en pensez :)

**Comment by florianpanchout** [comment]
Je n'ai pas trouvé plus parlant comme icône. C'est ce que Youtube utilise donc je me dis que ça parle à suffisamment de gens.

Oui c'est le but de généraliser toute cette partie. Je fais mes tests sur http://teletravail.monimpacttransport.fr/ et quand tout sera bon je l'étendrai aux autre simulateurs.

J'aimerais généraliser les deux boutons côte à côte en bas aussi "Je partage mon résultat" et "j'intègre ce simulateur à mon site". Ça permettrais d'avoir les deux icones toujours visibles (mais pas forcement comprises par tous) et les boutons textes lorsque l'on a fais une simulation.

Pour MIT, il suffira de mettre la roue cranté de l'autre côté :)

**Comment by martinregner** [comment]
> Je n'ai pas trouvé plus parlant comme icône. C'est ce que Youtube utilise donc je me dis que ça parle à suffisamment de gens.

Ok ok...
... on te dira avec @Clem-mrtn selon les retours ;)

> Oui c'est le but de généraliser toute cette partie. Je fais mes tests sur http://teletravail.monimpacttransport.fr/ et quand tout sera bon je l'étendrai aux autre simulateurs.

Top 👍 

> [...] boutons textes lorsque l'on a fais une simulation.

C'est à dire en bas ? Ou ils ne s'affichent que si tu as interagi avec le simulateur ?

**Comment by florianpanchout** [comment]
J'ai rajouté des tooltip au survol :)

J'ai ajouté la partie contact à droite aussi. Vous en pensez quoi ?


> C'est à dire en bas ? Ou ils ne s'affichent que si tu as interagi avec le simulateur ?

Les deux boutons qui s'affichent lorsque l'on a complété la simulation

**Comment by martinregner** [comment]
>

**Comment by martinregner** [comment]
> J'ai ajouté la partie contact à droite aussi. Vous en pensez quoi ?

Top ! On retravaillera le contenu ensemble mais c'est très bien je trouve sur le côté.

> J'ai rajouté des tooltip au survol :)
Où ça ? Pas trouvé 😋

**Comment by Clem-mrtn** [comment]
Si je résume, les dernières issues à traiter : 

- Remonter le bouton "J'intègre le simulateur à mon site" au dessus des "30%.." pour clarifier & prioriser le call to action 
- Retravailler le texte **_"Nous contacter"_** pour clarifier le message 
     => Nous contacter = formulaire des issues qui remontent soit dans Github directement soit dans Airtable. Pas de demande 
     d'intégration
- Intégrer le bloc _**"Comment intégrer ces données à mon site ou app"**_ dans le slider, sous les différents thèmes (comme pour Télétravail) 
- Rajouter les boutons **_Partager_**, **_Intégrer_** & **_Nous Contacter_**

**Comment by florianpanchout** [comment]
Done
