### ISSUE TITLE
Autre design - Couleurs mode Classique

### ISSUE THREAD

**Issue by fjg** [datagir/monimpacttransport#43]
- [ ] Je trouve les couleurs moins bien séparées (barre d'émissions + options comme le covoiture) contrairement au design par défaut (bleu foncé, rose, bleu ciel)

cf.
<img width="1351" alt="Capture d’écran 2021-03-16 à 17 44 03" src="https://user-images.githubusercontent.com/91435/111347962-a278fb80-8677-11eb-9f33-29e1d5484974.png">

Et les 3 carrés en couleur de chaque design, deux sont tjs de la même couleur, normal ?

- [ ] Sauf le design standard, tous les autres n'ont que 2 couleurs :p 
- [ ] la carte ne s'affiche pas sur les autres designs

**Comment by florianpanchout** [comment]
J'ai modifié.

Ces thèmes sont fait pour être plus simples que le thème par défaut. D'ou les deux couleurs et l'absence de carte
