### ISSUE TITLE
Bug Kilométrage 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#54]
J'ai l'impression qu'il y a un bug lorsque l'on renseigne les Km 
Quand je veux effacer une distance ça me remet automatiquement à 10Km au lieu d'avoir un champs vide pour que je puisse renseigner mes Km

Et cas d'usage : quand je mets 1Km et que j'efface ça me remet automatiquement 10Km
c'est fait exprès ?

**Comment by florianpanchout** [comment]
Nope c'est un bug. C'est corrigé
