### ISSUE TITLE
Ajouter un bouton partage

### ISSUE THREAD

**Issue by florianpanchout** [datagir/monimpacttransport#55]
Ce serait interessant d'avoir un bouton de partage sur tous les simulateurs non ?

Pour copier coller l'url avec ou sans la recherche en cours 
Pour envoyer l'url par mail
Pour la partager sur Facebook/Twitter/Linkedin

Qu'en pensez vous @Clem-mrtn @martinregner ?

**Comment by florianpanchout** [comment]
J'ai mis en ligne une première proposition de partage ici : https://teletravail.monimpacttransport.fr/

J'ai mis Mail, Facebook, Twitter, Linkedin et Whatsapp en option. Vous en voyez d'autres ?

Il faudra aussi penser à écrire des messages de partage pour chaque reseau social

**Comment by martinregner** [comment]
Top 👍 
Génial la fonction de selec de partage du simulateur ou du résultat !

On est déjà pas mal là en termes de mode de partage ^^

On verra le nombre de clics aussi dans matomo ?

**Comment by florianpanchout** [comment]
Ah cool, j'avais peur que cette option ne soit pas évidente :)

Oui on pourra tracker tout ça :)
