### ISSUE TITLE
Raccourci webapp sur mobile

### ISSUE THREAD

**Issue by martinregner** [datagir/monimpacttransport#59]
Est-ce possible de mettre un bouton qui s'afficherait sur mobile qui permettrait d'ajouter le site en webapp ou donnerait une marche à suivre (de [ce genre](https://www.mobizel.com/mettre-un-site-mobile-sur-son-ecran-daccueil/)) ?

**Comment by florianpanchout** [comment]
C'est fait :)

**Comment by martinregner** [comment]
Cool ! Ca s'affiche où @florianpanchout ? (pas encore vu sur mon tel mais p-e problème de cache)

**Comment by florianpanchout** [comment]
Aah je croyais que tu voulais juste rendre l'app installable. 

Je regarde ce qu'il est possible de faire

**Comment by martinregner** [comment]
J'ai encore eu la question ce matin en interne @florianpanchout sur la dispo en "app" des simulateurs. Il y a un public je pense 😃 
Un simple bouton ou raccourci qui s'afficherait que sur mobile serait top pour un peu "automatiser" l'installation (sinon c'est quand même réservé aux connaisseurs...)

**Comment by florianpanchout** [comment]
C'est fait !

**Comment by martinregner** [comment]
Top ! Tu fais comment pour le voir ? Sur Firefox je vois pas où ça s'affiche @florianpanchout

**Comment by florianpanchout** [comment]
Avec les 3 autres boutons (embed, share, contact). Sur mobile et desktop.

Par contre il ne s'affiche que si l'app est installable. Donc si tu l'as déjà installé tu ne le verra plus (et je ne sais pas si tu l'auras à nouveau si tu la désinstalles. Chaque navigateur choisi lui même quand afficher le bouton ou non, je n'ai pas la main dessus)

**Comment by martinregner** [comment]
Parfait !
Ah bin oui, je l'ai déjà ;)
