### ISSUE TITLE
Précisions sur le périmètre

### ISSUE THREAD

**Issue by fjg** [datagir/monimpacttransport#6]
Etes-vous certain de la pertinence de votre modèle? Deux remarques de fonds : 
1) vous n'intégrez manifestement que le coup marginal d'émission de CO2 du mode de transport, pas le coût CO2 total, incluant le coût de production du mode de transport, ni la durée de vie du mode choisi. Trottinettes et vélos électriques (moins de trois mois de durée de vie d'après les fournisseurs eux-mêmes) sont de ce point de vue d'une efficience écologique qu'on peut questionner...
2) vous semblez raisonner en calcul d'émission directes marginales, en pénalisant de ce fait les transports en commun : métros, tramways et bus circulent de toute façon, que vous montiez dedans ou circuliez à côté par un autre mode de transport urbain. A nouveau, lire qu'utiliser une trottinette ou ou vélo électrique émettrait moins de CO2 que prendre le métro ou un tramway me semble un calcul complètement biaisé.

**Comment by fjg** [comment]
Le simulateur ne compare bien que ce qui est comparable : l'usage du mode de transport et non du cycle de vie entier (fabrication de la trottinette ou de l'infrastructure - route par exemple, etc.).

**Comment by fjg** [comment]
Autre retour en lien :

```
Avoir des données que l'on peut afficher en prenant en compte tout le cycle de vie, ou juste le kilométrage. 

Pour certains modes de transport cela peut faire varier très fortement les impacts (de 2g CO2 KM pour la trottinette contre 60 g CO2 en ACV) (source : https://www.bird.co/fr/blog/analyse-cycle-vie-revele-vaste-ecart-emissions-co2-entre-voitures-trottinettes/) 

Du coup, si on considère les données hors ACV, on a une vision vraiment faussé de l'impact de ce mode de transport par rapport aux autres.
```

**Comment by fjg** [comment]
Votre calcul ne prend pas en compte l'empreinte complète d'un équipement ramenés au km. Ainsi certain équipements électriques type trottinette sur leur durée de vie totale ont une empreinte supérieure à celle de petites motos voire voitures thermiques.

**Comment by florianpanchout** [comment]
Done (affiché en bas comme dans l'ancien simulateur)

**Comment by martinregner** [comment]
Ok très bien.
Tu peux rajouter le début "Équivalent CO₂ par personne en France" ? C'est important d'afficher que c'est valable qu'en France.

En dessous de 7 lignes de moyens de transport, le texte reste en bas, laissant un espace avec les barres au-dessus. Serait-il possible que ce soit toujours "collé" sous la dernière barre, même quand il n'y en a moins de 7 ? (cela permettra notamment de réduire la taille de la page / l'iframe)

**Comment by florianpanchout** [comment]
Le texte s'affiche en bas de l'écran lorsque il reste de l'espace. Dans tous les cas le texte d'information à la suite s'affiche sous la ligne de flottaison pour ne pas surcharger l'écran lorsque l'on arrive sur le site. 
Ce n'est pas le cas sur l'iframe ou on ne prends pas en compte la taille de l'écran.
