### ISSUE TITLE
Grossir le + de détails et mettre en avant le covoiturage

### ISSUE THREAD

**Issue by martinregner** [datagir/monimpacttransport#65]
Nouveau retour (ré)utilisateur qu'on a eu avec @Clem-mrtn sur le fait qu'on ne comprend pas que :
- les barres sont cliquables
- qu'il est possible d'ajouter des covoitureurs

Proposition : **grossir le "+" et ajouter un smiley à côté ex** " ➕ 👨 "

**Comment by florianpanchout** [comment]
C'est mieux ?

**Comment by martinregner** [comment]
Plus clair avec le nouveau design oui.
Mais tu pourrais tester avec un bonhomme à côté du + ?

+ un tooltip au survol ? ex : Ajouter des passagers

**Comment by Clem-mrtn** [comment]
Ou à défaut d'avoir une tête à côté, ajouter une animation ? Genre le bouton tourne ou autre ?
(+1 pour le tooltip aussi)

**Comment by florianpanchout** [comment]
J'ai ajouté un tooltip

**Comment by martinregner** [comment]
Tu as testé aussi avec un petit smiley à côté du + ? :)
Sans forcément l'implémenter tu penses que tu pourrais juste nous faire une "capture d'écran" de ce que ça donnerait ?

**Comment by florianpanchout** [comment]
J'ai fait un essai. Pas convaincu que ça soit plus lisible

**Comment by martinregner** [comment]
cool, testons ! on peut voir les interactions spécifiques avec ce bouton là ?

**Comment by florianpanchout** [comment]
On peut voir le nombre d'ouverture du panneau de configuration mais pas via ce bouton spécifiquement. Après vu que c'est le seul changement, on pourra voir la différence

**Comment by Clem-mrtn** [comment]
Cool ! Mais c'est marrant moi je l'aurais plutôt fait dans l'autre sens 
" + et ensuite la tête du bonhomme"
