### ISSUE TITLE
Rendre plus évident le Bouton "Itinéraire vol d'oiseau"

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#67]
(Je ne sais pas comment s'appelle ce bouton 😸 ) 
Mais un réutilisateur nous a dit qu'il n'avait pas vu l'option **"Rentrer un itinéraire"** (le bouton du haut qui permet de switcher).

Peut-être pourrait-on d'avantage l'animer pour le rendre plus visible ? Notamment dans cette dernière version

**Comment by florianpanchout** [comment]
Il bougeait (de façon excessivement énervante) avant. Du coup je doute qu'une animation soit la solution. Je l'ai enlevé pour mettre en avant l'input plutôt.

J'ai changé sa forme pour qu'il ressemble plus à un bouton en mode iframe. On peut attendre de voir ce que ça donne

À noter : On a plus d'1/3 des gens qui interagissent avec le simulateur qui cliquent sur ce bouton. Je n'arrive pas à savoir si c'est bien ou pas

**Comment by martinregner** [comment]
> Il bougeait (de façon excessivement énervante) avant. Du coup je doute qu'une animation soit la solution. Je l'ai enlevé pour mettre en avant l'input plutôt.

Et le faire juste clignoter comme l'input km ? Peut-être un peu moins fréquemment, mais ça attire bien l'oeil et c'est assez sobre.

> J'ai changé sa forme pour qu'il ressemble plus à un bouton en mode iframe. 

👍 👍 

> À noter : On a plus d'1/3 des gens qui interagissent avec le simulateur qui cliquent sur ce bouton. 

A pas mal déjà. Il est totalement invisible c'est déjà ça.

**Comment by Clem-mrtn** [comment]
Hum ouais mais je crains que certains réutilisateurs passent quand même à côté 
Sinon rajouter un énième tooltip ? Ou pq pas l'animation des KM

**Comment by martinregner** [comment]
cf. https://github.com/datagir/monimpacttransport/issues/74
