### ISSUE TITLE
Garder la voiture seule pour mettre en avant le covoiturage 

### ISSUE THREAD

**Issue by martinregner** [datagir/monimpacttransport#68]
Un retour (ré)utilisateur qu'on a eu avec @Clem-mrtn me parait très intéressant : rendre possible la comparaison entre voiture seule et covoiturage.

Je vois 2 options : 
1. Permettre d'afficher des lignes (cachées par défaut) qui montrent : voiture à 2, voiture à 3, voiture à 4, voiture à 5
2. Rendre possible de distinguer la voiture seule par rapport au covoit dès que l'on rentre des covoitureurs

Petite préférence pour la 2.
Dès que l'on ajoute des covoitureurs, la ligne voiture seule se sépare (seulement la voiture thermique dans un premier temps) et la ligne covoiturage reste à part (les autres lignes où des passagers s'ajoutent gardent le comportement actuel et évoluent aussi en fonction du nombre de personnes).
Eventuellement : on peut désactiver (ou l'activer si pas par défaut ?) cette fonction via les paramètres.

Qu'en pensez-vous ?

**Comment by Clem-mrtn** [comment]
Carrément je trouve que ça met encore plus l'accent sur l'impact !

**Comment by florianpanchout** [comment]
Traité dans la v3

**Comment by Clem-mrtn** [comment]
![image](https://user-images.githubusercontent.com/76995768/148805735-b719a6db-64ec-4aaa-a2c9-352b43cfcc4e.png)
![image](https://user-images.githubusercontent.com/76995768/148805823-4a896b09-aaec-4c84-9f95-7b8169118514.png)

Je trouve que ce nouvel affichage surcharge beaucoup la simulation... 
On pourrait p-t trouver un compromis : 
- On coche l'option "Afficher le covoiturage" 
- Au coche, une barre covoit apparaît sous chaque véhicule concerné 
- Et sur cette même barre on peut jouer avec le nombre de covoitureurs (2, 3, 4 etc.) 

=> Le but est de se rendre compte que le covoiturage a un impact positif vs. la voiture seule par exemple 
et pas un besoin vitale à mon sens de comparer une voiture avec 2 covoitureurs et une voiture avec 3 covoitureurs. 
On verrait bien dans la simulation que l'impact diminue 

Qu'en pensez-vous ?

**Comment by florianpanchout** [comment]
Done

**Comment by Clem-mrtn** [comment]
Top, + clair comme ça :) 
Par contre il manque la possibilité de mettre des covoitureurs sur moto légère & moto ?

**Comment by Clem-mrtn** [comment]
Pour le mode itinéraire le covoit s'affiche par défaut alors que la case n'est pas cochée : 
![image](https://user-images.githubusercontent.com/76995768/148963302-026cb7b6-5053-4201-820a-8dc659790be9.png)

**Comment by florianpanchout** [comment]
> Par contre il manque la possibilité de mettre des covoitureurs sur moto légère & moto ?

Ah oui je les ai enlevé pour simplifier mes devs, et au moment de les rajouter je me suis demandé si c'était nécessaire. J'ai l'impression que l'on surcharge et complique l'interface (leur nombre de covoitureur ne pouvant pas être constant avec les voitures), et surtout que l'on brouille la différence passager / covoitureur (message que l'on galère déjà à faire passer). Est ce que le covoiturage en moto / scooter existe vraiment ?

Je suis preneur de vos avis

**Comment by Clem-mrtn** [comment]
Hum, je dirais que d'avoir un covoit/passager sur une moto peut éviter à cette deuxième personne de prendre son propre moyen de transport (et donc éviter qu'elle prenne par ex sa propre voiture toute seule, ou sa propre moto). 
Donc pour moi cela a quand même une incidence 

Proportionnellement, dans la simulation, sur 15 KM par exemple est-ce que cela est bien visible la différence entre scooter/moto sans passager et avec passager ?

Si on voit bien une différence, je trouve ça dommage de pas le mettre en avant, si c'est anecdotique effectivement je sais pas trop

**Comment by florianpanchout** [comment]
Il y a forcement une différence visible puisque l'on divise l'impact par deux. La question que je pose c'est : qui fait du covoiturage en moto ? 

J'ai surtout peur qu'en l'état les gens, ne pouvant imaginer du covoiturage en moto, regardent cette ligne et comprennent "passager" plutôt que "covoitureur", ce qui fausse totalement le calcul.

**Comment by Clem-mrtn** [comment]
Mais je comprends pas trop : le passager peut être un covoitureur ? S'il n'est pas dans le même véhicule c'est qu'il peut être dans un autre ? 
C'est quoi la différence de calcul ?

**Comment by Clem-mrtn** [comment]
Au delà du mot/méthodo @martinregner qu'en penses-tu ? Pertinent de l'afficher ou pas ?

**Comment by Clem-mrtn** [comment]
Ah ouii ok je comprends c'est forcément pour un même trajet.
Mais y a des subtilités pourtant : tu peux être passager d'une voiture, et te faire déposer par exemple quelque part sur le trajet du conducteur et pour autant ce n'est pas le même trajet, et ça t'as économisé un trajet dans ton propre véhicule

**Comment by florianpanchout** [comment]
Oui je suis d’accord. C’est pour ça que je ne suis pas non plus à l’aise avec l’affichage actuel. Mais je pense que c’est le mieux que l’on puisse faire sans entrer dans une UI beaucoup plus complexe.

Ça pourrait à terme faire l’objet d’un nouveau mode du simulateur (comme le mode télétravail) pour avoir plus de précision
