### ISSUE TITLE
Nouveau bandeau iframe (intégrer, partager, contact, version détaillée)

### ISSUE THREAD

**Issue by martinregner** [datagir/monimpacttransport#69]
Très bonne idée ce bandeau en iframe ! 👍 

Au clic on ne voit pas qu'un menu si on est trop en bas / si l'écran est pas assez grand.
Il faudrait ouvrir tous les menus plutôt au dessous des boutons, pour :
- intégrer
- partager
- contact

Le bouton version détaillée ne fonctionne pas sur mon ordi (Chrome)

**Comment by florianpanchout** [comment]
Corrigé !

**Comment by martinregner** [comment]
Génial !!
Pareil sur les autres ? 🤩

**Comment by florianpanchout** [comment]
Soon
