### ISSUE TITLE
Barre de l'avion coupée en deux

### ISSUE THREAD

**Issue by mquandalle** [datagir/monimpacttransport#73]
![image](https://user-images.githubusercontent.com/1730702/123072271-ae621f80-d415-11eb-82e2-78cbca7bc760.png)

En voyant cette barre coupée en 2 j'ai eu l'impression que c'était une “ellipse” pour signifier que la barre n'était pas à l'échelle par rapport aux autres grandeurs au dessus.

En regardant les nombres correspondants j'ai vu que c'était bien à l'échelle puis trouvé que la deuxième section correspondait à l'impact des traînées. Pour éviter cette confusion je ne mettrais pas d'espace entre les deux sections, mais privilégiais une variation de couleur voire un motif hachuré.

**Comment by laem** [comment]
Je pense qu'il est non pertinent de séparer pour l'avion l'empreinte ainsi. 
- c'est une complexité impossible à comprendre pour la personne lambda
- si l'on sépare l'effet des GES de l'avion, il semble légitime de le faire pour les autres lignes aussi, certaines ayant une part non-CO2 non négligeable (exemple, le pétrole dont l'extraction émet je crois du méthane)

**Comment by laem** [comment]
Une étude de l'ADEME très pertinente à ce sujet est sortie récemment en avril 2021.

[ademe-citepa-rapport-final-trainees-aerien-202104.pdf](https://github.com/datagir/monimpacttransport/files/7564574/ademe-citepa-rapport-final-trainees-aerien-202104.pdf) 

https://librairie.ademe.fr/mobilite-et-transport/4617-etat-de-l-art-de-la-recherche-scientifique-sur-l-impact-climatique-des-trainees-de-condensation-des-avions.html

@martinregner je remarque que ce n'est pas un PDF "cherchable"

La conclusion n'est pas évidente à interprêter, mais je pense que ça pousse quand même en faveur de simplifier notre affichage avec une seule barre.

**Comment by martinregner** [comment]
@florianpanchout, le sujet revient en interne, soulignant que cela pose un problème de cohérence par rapport aux réglementations/normes « transport » qui excluent les émissions des trainées, même si l’ISO 14064-1 (Bilan GES des entreprises) ne les exclue pas et indique la possibilité de les prendre en compte, de la même manière que la méthode réglementaire française pour les Bilans GES.

L'affichage actuel pose donc problème. Il faudrait donc afficher les deux avec et sans.
Pour l'affichage, je propose 2 lignes : 
- Avion (sans impacts des trainées)
- Avion (avec impacts des trainées)

L'info bulle devient donc juste une information qui explique les trainées, plus de case à cocher.
On perd un peu en clarté d'UX mais on gagne par ailleurs auprès de ceux qui croisent des valeurs différentes et verront ici clairement pourquoi.

**Comment by laem** [comment]
Je crains que du point de vue utilisateur, ce soit perturbant que l' "agence pour l'environnement", autorité à leurs yeux, affiche une telle incertitude en 1ère lecture, même si l'incertitude derrière est bien réelle évidemment (et documentée dans le doc ADEME plus haut :arrow_double_up:).

Les émissions de la voiture, du bus, du scooter, sont elles aussi très incertaines (mais pour d'autres raisons : principalement car la gamme de matériel utilisé est extrêmement variable, de la Twingo au SUV de 2,5 tonnes par exemple). Si l'incertitude sur ces barres était résolue par des boutons aussi en 2ème lecture, ou une duplication des barres, celle sur l'avion donnerait moins l'impression d'une étrange exception. 

> aux réglementations/normes « transport » qui excluent les émissions des trainées

Si les données présentées dans le simulateur sont cadrées par des réglementations ou normes transport précises je pense qu'il faur qu'on les indique dans les sources du simulateur.

**Comment by martinregner** [comment]
Comme échangé, pour être cohérent avec l'[_Information GES des prestations de transport_](https://www.ecologie.gouv.fr/information-ges-des-prestations-transport) (pour trouver les bons FE il faut aller dans [cet article ](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000034502741#JORFTEXT000034502741)qui est listé dans les liens en bas de page) et garder une UX compréhensible, nous partons, au moins dans un premier temps sur : 
- le décochage par défaut des trainées
- la modification de la modale pour expliquer cette source ; proposition : 

> **Impact des traînées**
> Du fait que les avions volent à haute altitude, la combustion du kérosène crée des traînées et perturbe les cycles d’autres gaz à effet de serre que le CO2 (vapeur d'eau, eau condensée sous diverses formes, NOx et méthane qui, ensemble, produisent de l'ozone, etc.). Cet impact est appelé forçage radiatif additionnel.
Dans l'[Information GES des prestations de transport](https://www.ecologie.gouv.fr/information-ges-des-prestations-transport) réglementaire, cet impact n'est pas inclus. Vous pouvez le visualiser en cochant la case ci-dessous.
 [ ] Afficher l'impact des traînées

**Comment by florianpanchout** [comment]
Je pense qu'il est beaucoup trop ambitieux de faire comprendre le principe de forçage radiatif à nos utilisateurs au premier coup d'oeil. La barre coupée en deux ne me dérangeait pas parce que je partait du principe que les gens ne la remarquaient pas (et donc que ça ne servait à rien).

Tant que l'on a pas expliqué ce principe d'effet des trainées aux gens, on ne peut pas leur montrer deux chiffres. Hors il est à mon sens trop complexe pour qu'on puisse l'expliquer en premier niveau de lecture.

Je préfère que l'on se conforme à la législation et qu'on affiche par défaut sans l'effet des trainées plutôt que d'essayer d'afficher les deux en même temps.

Par contre il serait peut être intéressant de mettre plus en avant la modale qui explique le forçage radiatif pour les utilisateurs qui sont prêt à ce niveau d'information.

**Comment by martinregner** [comment]
Ok je te rejoins @florianpanchout.
Donc checkbox trainée décochée par défaut et la modale deviendrait :

>**Impact des traînées**
Du fait que les avions volent à haute altitude, la combustion du kérosène crée des traînées et perturbe les cycles d’autres gaz à effet de serre que le CO2 (vapeur d'eau, eau condensée sous diverses formes, NOx et méthane qui, ensemble, produisent de l'ozone, etc.). Cet impact est appelé forçage radiatif additionnel.
Dans l'[Information GES des prestations de transport](https://www.ecologie.gouv.fr/information-ges-des-prestations-transport) réglementaire, cet impact n'est pas inclus. Vous pouvez visualiser l'impact des traînées tel que proposé dans la Base Carbone(r) en cochant la case ci-dessous.
[ ] Afficher l'impact des traînées

**Comment by laem** [comment]
> un dégradé sur la barre avion, qui représente l'incertitude d'une façon moins perturbante que la séparation franche qui a donné cette issue initialement.

Je continue de penser que c'est une solution à envisager, au moins à tester. 

![image](https://user-images.githubusercontent.com/1177762/154301073-f07ce7e9-b075-45a1-bede-80a552646315.png)

Le problème de la différence de traitement de l'incertitude entre l'avion et les autres moyens de transport reste entière, mais ce sera le cas quelque soit la méthode de représentation utilisée.

**Comment by florianpanchout** [comment]
Ce qui ne résout pas le problème de devoir légalement afficher la valeur sans forçage radiatif.

**Comment by laem** [comment]
> Ce qui ne résout pas le problème de devoir légalement afficher la valeur sans forçage radiatif.

La loi n'oblige pas à ne prendre en compte que le facteur sans traînées. Elle donne une base qu'on pourrait interpréter comme "minimale" de facteurs d'émissions et de méthodologie, mais parle notamment de mention "méthode spécifique" libre d'utilisation par le prestataire s'il en dispose d'une, tant que le calcul est "sincère". 

On note aussi que l'[arrêté 26 avril 2007](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000034502741#JORFTEXT000034502741) corrige la loi pour parler de GES et plus uniquement de CO2. 

> les mots : « dioxyde de carbone» sont remplacés par les mots : « gaz à effet de serre (dioxyde de carbone équivalent ou CO2e) ».

monimpacttransport.fr n'est pas soumis à cette loi, même si bien sûr ça semble logique d'en faire un calculateur qui se conforme à la base minimale de cette loi. Ce faisant, en minimisant (division par 2 ou 3) l'empreinte GES de l'aviation.

**Comment by laem** [comment]
> Je continue de penser que le dégradé est une solution à envisager, au moins à tester.

MAJ : **j'ai fait un test avec 2 utilisateurs, et l'incertitude de la barre n'est pas comprise.**

Déjà la première remarque sur la barre avion, c'est : mais c'est pour combien de personnes l'avion, parce que sur la barre voiture on voit clairement que c'est pour 1 ou 2 personnes ?

Une autre interprétation était plutôt pertinente : "ah, c'est la variation de l'empreinte en fonction de la distance car l'avion consomme plus au départ", mais pas la bonne. 

Après l'exposé du pourquoi du test et une longue et passionnée discussion sur les GES, leur conclusion est simple : ben montrez-nous les différents gaz qui composent les barres d'empreinte, comme ça on voit tout. Je m'attendais pas à un tel intérêt sur la décomposition de l'empreinte CO2 et CO2+vapeur d'eau + méthane x puissance ! Donc peut-être une piste à explorer dans un second temps en 2 ou 3ème lecture, pour aller plus loin. 

Je vais faire une autre issue intéressante sur un autre sujet :)

**Comment by florianpanchout** [comment]
Done (décochée par défaut)

**Comment by martinregner** [comment]
Comme discuté en point produit, cf. la modale sur Mon Impact Transport :
> Dans l'[Information GES des prestations de transport réglementaire](https://www.ecologie.gouv.fr/information-ges-des-prestations-transport), cet impact n'est pas inclus mais il est recommandé dans la réglementation pour la réalisation des Bilans GES des organisations.

l'impact des traînées n'est pas inclus pour des raisons réglementaires.

Vu l'usage de Mon Convertisseur CO2, proche d'un usage (voire persona) Bilan GES, il pourrait être pertinent d'inclure l'impact des traînées.

Pour des raisons de lisibilité et compréhension pour l'utilisateur (pas de traînées sur l'un des simulateurs, traînées sur l'autres, donc 2 chiffres différents) il est décidé à ce stade de maintenir ce qui est fait sur Mon Impact Transport sur les 2 (pas d'impact des traînées).

**Comment by Clem-mrtn** [comment]
>

**Comment by florianpanchout** [comment]
La nouvelle version sur mcc rends cette issue caduque
