### ISSUE TITLE
Améliorer le mode itinéraire

### ISSUE THREAD

**Issue by martinregner** [datagir/monimpacttransport#74]
Au moins pour tous les modes routiers (vélo, voiture, bus, scooter moto) intégrer une recherche de distance plus précise.

Permettrait de mettre le mode itinéraire par défaut.

**Comment by Clem-mrtn** [comment]
**MAJ de l'issue 07.09 :** 
Suite aux retours utilisateurs on constate que le bouton itinéraire est difficile à trouver 
Il faudrait l'optimiser pour qu'il apparaisse comme le choix par défaut et faire en sorte qu'on visualise bien les deux modes (Rentrer un nombre de KM / Rentrer un itinéraire)  

- [ ] Le faire apparaître par défaut en arrivant sur la page 
- [ ] Alléger le texte "Quand je vais... de..." qui peut être un peu lourd notamment sur mobile

**Comment by Clem-mrtn** [comment]
Donc t'aurais plus une évaluation par type de transport mais t'aurais seulement une barre "Transport en commun" avec la moyenne des émissions de TEC pour ton trajet ?

**Comment by florianpanchout** [comment]
On pourrais séparer métro / tramway /ter / tgv / ... et bus / autocar mais sinon oui. 

Tous les modes de transport "rail" sont assez proche en terme d'émission pour que les rassembler ne soit pas un non sens total. 

Pour bus / autocar c'est plus compliqué mais il est possible d'afficher bus jusqu'à une certaine distance puis autocar pour le reste.

Je pense que l'on dilue moins notre message et que les approximations de calcul sont compensées par le fait d'être sur d'afficher un trajet qui "existe" (vu que l'on prends moins de risque)

**Comment by martinregner** [comment]
Pour être sûr de comprendre : tous les transports par rail seraient des "transport en commun rail" ?
Pour des courtes distances c'est clair, mais pour un trajet en tgv ou intercité c'est pas très intuitif "TEC" je trouve.

**Comment by florianpanchout** [comment]
Peut être séparer `TER` et `TGV ou intercités` vu la différence d'impact

**Comment by martinregner** [comment]
@florianpanchout côté API pour les itinéraires il y a aussi https://navitia.io/ avec qui je viens d'échanger.
Sans doute que notre besoin pourrait être couvert par eux ? si ça t'intéresse on peut organiser un échange avec leur équipe tech

**Comment by florianpanchout** [comment]
Ils ne répondent malheureusement pas à notre besoin non plus. Je n'ai toujours pas trouvé mieux que Google pour ça :/

Pour l'instant je fais un appel pour calculer la distance à pied / en voiture / via rail. Si je n'ai pas la réponse via rail (donc il n'arrive pas à trouver un trajet en TEC entre les deux points), j'affiche la distance voiture à la place.

Et j'affiche les moyens de transport par groupement (en faisant la moyenne), selon le nombre de km.

Je pense que c'est le mieux que l'on puisse avoir jusqu'à ce qu'on passe au trajet multimodal (qui nécessitera un travail UX/dev important)

**Comment by florianpanchout** [comment]
J'ai modifié la façon dont sont traités les appels. Il faudra attendre quelques jours pour voir si c'est significatif ou non

**Comment by florianpanchout** [comment]
L'impact est visible mais pas suffisant. J'ai modifié la façon dont le sessiontoken est généré. Pareil, il faudra attendre quelques jours pour pouvoir mesurer  l'effet

**Comment by AntoineAugusti** [comment]
Les distances sont-elles multipliées par 2 ? Pour un Paris Bordeaux la valeur du TGV est incohérente si je cherche ensuite la distance donnée en kilomètres dans le premier onglet, 528km.

https://monimpacttransport.fr/itineraire?end=latitude-44.837789_longitude--0.57918_address-Bordeaux%2C%20France&start=latitude-48.856614_longitude-2.3522219_address-Paris%2C%20France

**Comment by florianpanchout** [comment]
Pour le mode itinéraire nous faisons une moyenne de différent mode de transport (ici TGV et intercités), afin de donner un ordre de grandeur cohérent tout en évitant d'afficher un trajet qui n'existe peut être pas (si pas de ligne TGV par exemple).

La valeur donnée pour cet itinéraire (1.83kg CO2e pour 514km) correspond bien à la moyenne entre le TGV et l'intercités pour cette distance (la légère différence est due à l'arrondi)

**Comment by Clem-mrtn** [comment]
Suite au message d' @AntoineAugusti 
Possible mise en relation avec Google pour optimiser l'API Google Maps

**Comment by florianpanchout** [comment]
Une alternative à GMap est visible ici : https://photon--ecolab-transport.netlify.app/

Les adresses sont suggérées et affichées via https://photon.komoot.io/

**Comment by Clem-mrtn** [comment]
J'ai fait quelques tests : 
- l'API fonctionne bien dans le sens où elle trouve toutes les adresses que je lui ai renseigné, elle indique les bon Km pour la distance et l'itinéraire.
- Il y a un peu de latence mais dans les fait elle est assez efficace 
- Vs. l'API Google, elle est juste moins précise et moins intuitive. 
Deux exemples, quand je fais une recherche : 
![image](https://user-images.githubusercontent.com/76995768/191463199-67086cac-0844-49d0-8fe6-bcb6b471f908.png)
![image](https://user-images.githubusercontent.com/76995768/191463331-1d0198c1-a094-4aee-940d-c0d39938b060.png)

On a pas le même niveau de précision et surtout elle est moins intuitive. Pour un lieu + spécifique il faut que je renseigne quasiment la totalité de l'adresse pour qu'elle propose le bon endroit, là où l'API Google est plus rapide. 

=> Pour l'usage, je pense que cette API alternative semble quand même bien fonctionner. 
Est-ce que cela impactera l'usage de notre API MIT ?

**Comment by florianpanchout** [comment]
Ça devrait au moins le diviser par deux normalement. Je viens de mettre en prod, on verra dans quelques jours

**Comment by Clem-mrtn** [comment]
> Ça devrait au moins le diviser par deux normalement


Diviser par deux quoi ?

**Comment by florianpanchout** [comment]
L'usage de l'API.
