### ISSUE TITLE
Test API Fnac-Darty 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#76]

**Comment by Clem-mrtn** [comment]
Quid de l'hébergement de l'API MIT sur Heroku ? (+ florian paye 7euros/mois)

=> Changer d'hébergeur ?

**Comment by florianpanchout** [comment]
L'api est maintenant une simple fonction Netlify ! Le nom de la fonction a changé : getEmissionsPerDistance

https://api.monimpacttransport.fr/beta/getEmissionsPerDistance?km=300

La doc est dans le Readme de ce repo (https://github.com/datagir/monimpacttransport)

(J'ai supprimé le projet sur Heroku, je laisse le repo https://github.com/datagir/monimpacttransport-api ouvert pour archive)
