### ISSUE TITLE
Bouton : Faire apparaître tous les modes de transport 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#78]
Intégrer un bouton qui permet d'afficher tous les modes de transport d'un coup sans avoir à cliquer sur chaque transport à chaque fois

**Comment by florianpanchout** [comment]
Bouton intégré dans la v3

**Comment by Clem-mrtn** [comment]
Ca me paraît très bien comme ça, effectivement plus "immédiat" que de passer par les paramètres. 
Mais du coup, on ne peut plus sélectionner soi-même les transports que l'on veut comparer ? C'est soit ceux par défaut soit tous ? 

**=> Pas forcément un PB juste se valider ce point :)** 

Aussi question, le "_tous_" est en surlignage bleue : on a envie de cliquer dessus mais ça n'ouvre rien. C'est pour + tard ? Ou ça n'ouvre rien ?
![image](https://user-images.githubusercontent.com/76995768/148781855-c60aedf1-1572-4e8c-b66c-fbe33b35e530.png)

**Comment by florianpanchout** [comment]
C'est la question. Est ce que l'on veut laisser ce choix à l'utilisateur ? J'ai l'impression que l'on complexifie l'app pour une fonction que quasiment personne n'utilise (j'ai trouvé une seule intégration qui utilise cette fonctionnalité : https://www.offways.fr/ ).

**Comment by florianpanchout** [comment]
Une option serait dans un premier temps de laisser la possibilité de choisir les modes de transport seulement via l'url.

Ça permettrais de ne pas casser l'intégration de offways tout en nous laissant le temps de la réflexion pour savoir si l'on souhaite réintégrer cette option et comment on pourrait afficher de façon compréhensible

**Comment by florianpanchout** [comment]
C'est en place sur v3
