### ISSUE TITLE
Vélo : toujours faire apparaître le vélo même à X km 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#79]
Aujourd'hui le vélo n’apparaît plus lorsque l’on dépasse X Km.
Afin de valoriser les transports vertueux, le maintenir afficher jusqu'à une limite de 100/200 ou 300 Km par exemple...

**Comment by florianpanchout** [comment]
Le vélo s'affiche maintenant jusqu'à 30km. Pour la suite, le bouton "Afficher tous les modes de transport" bien plus visible devrait permettre de répondre au problème non ?

**Comment by Clem-mrtn** [comment]
Moi ça me va pour cette v3 : dans les tests utilisateurs, on avait eu 1 ou 2 fois ce retour mais pas beaucoup plus.
Donc effectivement on peut laisser jsk 30 km et à voir en fonction des futurs retours users si c'est problématique au-delà de 30km _(ça concernerait ceux qui voyagent/ se déplacent pour de longs trajets en vélo...)_
