### ISSUE TITLE
Intégration sur un site - transportations id

### ISSUE THREAD

**Issue by fjg** [datagir/monimpacttransport#8]
Expliciter les transportations si ce sont des id de modes de transport à afficher ou pas. Par exemple dans le tableau en affichant l'id à côté, ou le préciser dans l'écran de partage.

```
<script id="datagir" src="https://monimpacttransport.netlify.app/iframe.js" data-search="?always=1&km=10000&mode=6&transportations=6_1_9_3_11_13_14_12_2_8_7_5_4&uncertainty=1"></script>
```

**Comment by florianpanchout** [comment]
On propose maintenant la choix des moyens de transport directement sur la configuration de l'iframe

**Comment by fjg** [comment]
nickel 👏

**Comment by fjg** [comment]
Le lien "Choisir les moyens de transports" n'est pas visible (over en souris ne change pas). Ptet lui donner un format bouton sinon ?

**Comment by fjg** [comment]
Ptet anecdotique, ajouter des tooltips sur le cadenas/oeil, je n'avais pas compris à quoi servait le cadenas.

**Comment by florianpanchout** [comment]
Fait
