### ISSUE TITLE
Validation des km : rajouter une flèche/bouton OK pour valider 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#81]
On peut chercher à valider une fois le km saisi (ne voit pas le changement immédiat) 
=> Du coup rajouter un bouton OK ou une flèche de validation pour se rendre compte que le nombre de km renseigné a bien été pris en compte et voir le changement des barre graphiques

**Comment by florianpanchout** [comment]
Problème réglé (dans la v3) par le changement d'input non ? Personne ne s'attend à valider après avoir utilisé le slider
