### ISSUE TITLE
Unité : par personne ou au total pour le véhicule ?

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#82]
Clarifier les unités

**Comment by florianpanchout** [comment]
Ajouté "par personne" dans l'intitulé dans la v3. Je ne sais pas comment le rendre encore plus compréhensible (tant que l'on a pas le taux de remplissage de tous les autres modes de transport)

**Comment by Clem-mrtn** [comment]
Je trouve ça clair !
