### ISSUE TITLE
"Bug" covoiturage : réinitialiser la simulation

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#83]
Une fois que l'on a fait une simulation en mode covoiturage le simulateur ne réinitialise pas le simulateur à 1 personne et reste avec le nombre de personnes renseigné dans une voiture => **peut fausser du coup la simulation si on fait une nouvelle recherche après.**
Aujourd'hui il faut recliquer sur les petits personnages pour revenir à une personne : **réinitialiser automatiquement** ?

**Comment by florianpanchout** [comment]
Avec le changement d'affichage du covoiturage et le changement d'input, je ne suis pas sur que cette réinitialisation soit nécessaire

**Comment by Clem-mrtn** [comment]
En effet avec ce nouveau mode le problème ne se pose plus mais je suis pas très fan du fait d'empiler les barres de comparaison pour 1,2,3,4 co-voitureurs 😬 
Je trouve que ça charge beaucoup l'écran de simulation... 

**J'aimais bien l'idée d'avoir une petite animation pour ajouter le nombre de co-voitureurs !** 

Mais je propose de traiter ce problème graphique dans une nouvelle issue ici : #88

Et on ferme celle-ci 😄
