### ISSUE TITLE
Afficher la définition de la trainé de l'avion directement au clique : regrouper les deux encarts

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#84]
Pour éviter trop de clics, au clic sur "+ - trainé de l'avion" : on ouvre directement sur cette fenetre avec la case à cocher : 

![image](https://user-images.githubusercontent.com/76995768/132357768-ec415786-fe1f-4419-b688-e97fb3e735cb.png)

**Comment by florianpanchout** [comment]
Fait dans la v3
