### ISSUE TITLE
Le bus semble assez catastrophique

### ISSUE THREAD

**Issue by laem** [datagir/monimpacttransport#86]
Retour utilisateur assez parlant : 

> C'est ouf que des que t'es 2 dans une voiture, c'est moins emetteur de CO2 que le bus (pour des petits trajets de 10km). Je ne m'y attendais pas du tout

Solutions possibles : 
- trouver le FE d'un bus électrique
- préciser pourquoi le bus a une empreinte si mauvaise : il est en moyenne peu rempli
- réfléchir à l'intégration d'un effet de réseau : tout comme pour une voiture on suppose que des covoitureurs s'arrangent entre eux, on pourrait imaginer un bouton pour le bus qui représente une espèce de mouvement citoyen, ou un truc du genre "si tout le monde fait comme toi".

**Comment by florianpanchout** [comment]
J'espère que la v3 rendra les choses plus claires (nouvel affichage des covoitureurs plus précision "par personne" dans l'intitulé.

Les deux sujets étant assez proche, je propose de continuer cette conversation ici : https://github.com/datagir/monimpacttransport/issues/82
