### ISSUE TITLE
Problème de suivi des stats

### ISSUE THREAD

**Issue by laem** [datagir/monimpacttransport#87]
@florianpanchout tu as essayé de voir si la lib matomo ne donne pas une fonction "onError" ou un truc comme ça ? 

https://github.com/datagir/monimpacttransport/blob/main/netlify/functions/getEmissionsPerDistance.js#L8-L10

**Comment by florianpanchout** [comment]
Bingo : 

`10:22:54 AM: 95303f01 INFO   error tracking request:  Client network socket disconnected before secure TLS connection was established`

**Comment by laem** [comment]
Cool ! Du coup t'as compris d'où vient le problème ?

**Comment by florianpanchout** [comment]
La fonction lambda s'arrêtait avant que l'appel à Matomo soit terminé. J'attend maintenant le retour du tracking avant de renvoyer le json
