### ISSUE TITLE
Changer l'icône du RER ou Transilien pour la différencier de l'intercités

### ISSUE THREAD

**Issue by fjg** [datagir/monimpacttransport#9]
Avec le mode je vais de ... à ... on peut se retrouver avec les 2 possibilités et visuellement on ne comprend pas pourquoi ce ne sont pas les chiffres.

Utiliser https://emojipedia.org/station/ 🚉 ou https://emojipedia.org/railway-car/ 🚃 pour le _RER/Transilien_ et garder l'icône actuelle 🚈 pour _Intercités_ et _TER_.

**Comment by florianpanchout** [comment]
Fait
