### ISSUE TITLE
Mode Télétravail (v3)

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#90]
![image](https://user-images.githubusercontent.com/76995768/148920756-a1926ec2-7850-4c91-aca0-a37a248b487e.png)
Clarifier le call to action "Télétravail" pour inciter l'utilisateur à switcher de mode 
- Passez en mode Télétravail
- Mode Télétravail 
- ....

**Comment by florianpanchout** [comment]
Modifié pour "Mode télétravail"
