### ISSUE TITLE
Permettre de faire une simulation sur des petites distances (< 10 KM) 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monimpacttransport#92]
![image](https://user-images.githubusercontent.com/76995768/150379083-63093b1c-5fca-4838-b51c-ce29aa9ccdd6.png)
Mettre le curseur :
- soit à 0 pour jouer sur les petites distances
- ou alors le positionner par défaut à 10KM mais pouvoir diminuer avec le curseur

**Comment by florianpanchout** [comment]
C'est fait, mais je ne suis pas sur de voir l'interêt. On rends l'ensemble du slider moins précis pour afficher un graph qui reste statique de 1 à 10.

**Comment by Clem-mrtn** [comment]
C'est pas faux ... 

Question : si on le laisse, pourquoi à l'affichage mettre le curseur sur 10km ?

**Comment by florianpanchout** [comment]
Parce qu'à zéro on afficherait pas de graph par défaut. Ou alors avec toutes les valeurs à 0 ?

Et pour le faire commencer à 10 plutôt qu'à 1 : je pense que c'est à 10km que les valeurs sont les plus compréhensibles (et probablement les plus proches de la réalité). C'est plus simple de comparer 0.02 à 1.93 (même si déjà pas évident) que 0.002 à 0.19.
